/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package refactor_gp_java_client;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
