/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package record.open.bci.with.json;

import org.junit.Test;

import record_open_bci_with_json.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
