/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package record_open_bci_with_json;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
